# @author yprakash
# Commands
# docker network create "py_network"
# docker-compose -f docker-compose-base.yml up -d

networks:
  py_network:
    external: true
    name: py_network
services:
  zookeeper:
    image: zookeeper:3.9.3
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
    networks:
      - py_network
  kafka:
    image: bitnami/kafka:3.8.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<host_ip>:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # below is required when you are running with a single-node cluster. If you have three or more nodes, you can use the default.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - "zookeeper"
    networks:
      - py_network
  mysql:
    image: mysql:9.1.0
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    networks:
      - py_network